package com.example.domain.engine

import android.graphics.Color as AndroidColor
import com.example.domain.model.AsciiMatrixResult
import com.example.domain.model.ExportLanguage
import com.example.domain.model.ExportStructure
import java.io.ByteArrayOutputStream
import java.util.zip.GZIPOutputStream

object CodeExporter {

    fun generateCode(
        matrix: AsciiMatrixResult,
        language: ExportLanguage,
        structure: ExportStructure,
        includeAnsi: Boolean,
        includeCliFunction: Boolean
    ): String {
        return when (language) {
            ExportLanguage.PYTHON -> generatePython(matrix, structure, includeAnsi, includeCliFunction)
            ExportLanguage.RUST -> generateRust(matrix, structure, includeAnsi, includeCliFunction)
            ExportLanguage.TYPESCRIPT -> generateTypeScript(matrix, structure, includeAnsi, includeCliFunction)
            ExportLanguage.GO -> generateGo(matrix, structure, includeAnsi, includeCliFunction)
            ExportLanguage.CPP -> generateCpp(matrix, structure, includeAnsi, includeCliFunction)
        }
    }

    private fun escapeAnsi(char: Char, colorInt: Int, includeAnsi: Boolean): String {
        if (!includeAnsi) return char.toString()
        val r = AndroidColor.red(colorInt)
        val g = AndroidColor.green(colorInt)
        val b = AndroidColor.blue(colorInt)
        return "\\033[38;2;${r};${g};${b}m$char\\033[0m"
    }

    private fun generatePython(
        matrix: AsciiMatrixResult,
        structure: ExportStructure,
        includeAnsi: Boolean,
        includeCli: Boolean
    ): String {
        val sb = StringBuilder()
        sb.append("# Generated by AsciiCraft v1.4 • ${matrix.sourceName}\n")
        sb.append("# Resolution: ${matrix.cols}x${matrix.rows} • ${matrix.glyphCount} glyphs\n")
        sb.append("import sys, time\n\n")

        if (includeAnsi) {
            sb.append("# ANSI Truecolor Palette definitions\n")
            sb.append("RESET = \"\\033[0m\"\n")
            sb.append("GREEN = \"\\033[38;2;63;185;80m\"\n")
            sb.append("CYAN  = \"\\033[38;2;88;166;255m\"\n\n")
        }

        when (structure) {
            ExportStructure.MATRIX_2D -> {
                sb.append("ASCII_MATRIX: list[str] = [\n")
                matrix.lines.forEachIndexed { y, line ->
                    val escapedLine = line.replace("\\", "\\\\").replace("\"", "\\\"")
                    sb.append("    \"$escapedLine\",\n")
                }
                sb.append("]\n\n")
            }
            ExportStructure.MULTILINE_RAW -> {
                sb.append("ASCII_ART: str = \"\"\"\n")
                sb.append(matrix.fullText)
                sb.append("\n\"\"\"\n\n")
            }
            ExportStructure.BYTES_GZIP -> {
                val gzipped = gzipString(matrix.fullText)
                sb.append("import gzip, base64\n\n")
                sb.append("GZIP_DATA = base64.b64decode(\"$gzipped\")\n")
                sb.append("ASCII_ART = gzip.decompress(GZIP_DATA).decode('utf-8')\n\n")
            }
            ExportStructure.CLI_STANDALONE -> {
                sb.append("ASCII_CANVAS = [\n")
                matrix.lines.forEach { line ->
                    val esc = line.replace("\\", "\\\\").replace("\"", "\\\"")
                    sb.append("    \"$esc\",\n")
                }
                sb.append("]\n\n")
            }
        }

        if (includeCli) {
            sb.append("def print_canvas(delay: float = 0.01):\n")
            sb.append("    \"\"\"Displays the ASCII Art with smooth scanline terminal animation\"\"\"\n")
            when (structure) {
                ExportStructure.MATRIX_2D, ExportStructure.CLI_STANDALONE -> {
                    sb.append("    for line in ASCII_MATRIX:\n")
                    sb.append("        print(line)\n")
                    sb.append("        time.sleep(delay)\n\n")
                }
                ExportStructure.MULTILINE_RAW, ExportStructure.BYTES_GZIP -> {
                    sb.append("    for line in ASCII_ART.splitlines():\n")
                    sb.append("        print(line)\n")
                    sb.append("        time.sleep(delay)\n\n")
                }
            }
            sb.append("if __name__ == '__main__':\n")
            sb.append("    print_canvas()\n")
        }

        return sb.toString()
    }

    private fun generateRust(
        matrix: AsciiMatrixResult,
        structure: ExportStructure,
        includeAnsi: Boolean,
        includeCli: Boolean
    ): String {
        val sb = StringBuilder()
        sb.append("// Generated by AsciiCraft v1.4 (Rust 1.75+)\n")
        sb.append("// Resolution: ${matrix.cols}x${matrix.rows}\n\n")

        when (structure) {
            ExportStructure.MATRIX_2D, ExportStructure.CLI_STANDALONE -> {
                sb.append("pub const ASCII_MATRIX: &[&str] = &[\n")
                matrix.lines.forEach { line ->
                    val esc = line.replace("\\", "\\\\").replace("\"", "\\\"")
                    sb.append("    \"$esc\",\n")
                }
                sb.append("];\n\n")
            }
            ExportStructure.MULTILINE_RAW -> {
                sb.append("pub const ASCII_ART: &str = r#\"\n")
                sb.append(matrix.fullText)
                sb.append("\n\"#;\n\n")
            }
            ExportStructure.BYTES_GZIP -> {
                val gzipped = gzipString(matrix.fullText)
                sb.append("pub const GZIP_BASE64: &str = \"$gzipped\";\n\n")
            }
        }

        if (includeCli) {
            sb.append("pub fn print_canvas() {\n")
            sb.append("    for row in ASCII_MATRIX {\n")
            sb.append("        println!(\"{}\", row);\n")
            sb.append("    }\n")
            sb.append("}\n\n")
            sb.append("fn main() {\n")
            sb.append("    print_canvas();\n")
            sb.append("}\n")
        }

        return sb.toString()
    }

    private fun generateTypeScript(
        matrix: AsciiMatrixResult,
        structure: ExportStructure,
        includeAnsi: Boolean,
        includeCli: Boolean
    ): String {
        val sb = StringBuilder()
        sb.append("/**\n * Generated by AsciiCraft v1.4 (TypeScript)\n * Size: ${matrix.cols}x${matrix.rows}\n */\n\n")

        when (structure) {
            ExportStructure.MATRIX_2D, ExportStructure.CLI_STANDALONE -> {
                sb.append("export const ASCII_MATRIX: readonly string[] = [\n")
                matrix.lines.forEach { line ->
                    val esc = line.replace("\\", "\\\\").replace("`", "\\`")
                    sb.append("  `$esc`,\n")
                }
                sb.append("] as const;\n\n")
            }
            ExportStructure.MULTILINE_RAW -> {
                sb.append("export const ASCII_ART: string = `\n")
                sb.append(matrix.fullText.replace("`", "\\`"))
                sb.append("\n`;\n\n")
            }
            ExportStructure.BYTES_GZIP -> {
                val gzipped = gzipString(matrix.fullText)
                sb.append("export const GZIP_PAYLOAD = \"$gzipped\";\n\n")
            }
        }

        if (includeCli) {
            sb.append("export function printCanvas(): void {\n")
            sb.append("  ASCII_MATRIX.forEach((line) => console.log(line));\n")
            sb.append("}\n\n")
            sb.append("printCanvas();\n")
        }

        return sb.toString()
    }

    private fun generateGo(
        matrix: AsciiMatrixResult,
        structure: ExportStructure,
        includeAnsi: Boolean,
        includeCli: Boolean
    ): String {
        val sb = StringBuilder()
        sb.append("// Generated by AsciiCraft v1.4\npackage main\n\nimport (\n\t\"fmt\"\n)\n\n")

        when (structure) {
            ExportStructure.MATRIX_2D, ExportStructure.CLI_STANDALONE -> {
                sb.append("var AsciiMatrix = []string{\n")
                matrix.lines.forEach { line ->
                    val esc = line.replace("\\", "\\\\").replace("\"", "\\\"")
                    sb.append("\t\"$esc\",\n")
                }
                sb.append("}\n\n")
            }
            ExportStructure.MULTILINE_RAW -> {
                sb.append("const AsciiArt = `\n")
                sb.append(matrix.fullText)
                sb.append("\n`\n\n")
            }
            ExportStructure.BYTES_GZIP -> {
                val gzipped = gzipString(matrix.fullText)
                sb.append("const GzipPayload = \"$gzipped\"\n\n")
            }
        }

        if (includeCli) {
            sb.append("func PrintCanvas() {\n")
            sb.append("\tfor _, row := range AsciiMatrix {\n")
            sb.append("\t\tfmt.Println(row)\n")
            sb.append("\t}\n")
            sb.append("}\n\n")
            sb.append("func main() {\n")
            sb.append("\tPrintCanvas()\n")
            sb.append("}\n")
        }

        return sb.toString()
    }

    private fun generateCpp(
        matrix: AsciiMatrixResult,
        structure: ExportStructure,
        includeAnsi: Boolean,
        includeCli: Boolean
    ): String {
        val sb = StringBuilder()
        sb.append("// Generated by AsciiCraft v1.4 (C++20)\n#include <iostream>\n#include <vector>\n#include <string>\n\n")

        when (structure) {
            ExportStructure.MATRIX_2D, ExportStructure.CLI_STANDALONE -> {
                sb.append("const std::vector<std::string> ASCII_MATRIX = {\n")
                matrix.lines.forEach { line ->
                    val esc = line.replace("\\", "\\\\").replace("\"", "\\\"")
                    sb.append("    \"$esc\",\n")
                }
                sb.append("};\n\n")
            }
            ExportStructure.MULTILINE_RAW -> {
                sb.append("const std::string ASCII_ART = R\"(\n")
                sb.append(matrix.fullText)
                sb.append("\n)\";\n\n")
            }
            ExportStructure.BYTES_GZIP -> {
                val gzipped = gzipString(matrix.fullText)
                sb.append("const std::string GZIP_B64 = \"$gzipped\";\n\n")
            }
        }

        if (includeCli) {
            sb.append("void print_canvas() {\n")
            sb.append("    for (const auto& line : ASCII_MATRIX) {\n")
            sb.append("        std::cout << line << \"\\n\";\n")
            sb.append("    }\n")
            sb.append("}\n\n")
            sb.append("int main() {\n")
            sb.append("    print_canvas();\n")
            sb.append("    return 0;\n")
            sb.append("}\n")
        }

        return sb.toString()
    }

    private fun gzipString(input: String): String {
        val bos = ByteArrayOutputStream()
        GZIPOutputStream(bos).use { it.write(input.toByteArray(Charsets.UTF_8)) }
        return android.util.Base64.encodeToString(bos.toByteArray(), android.util.Base64.NO_WRAP)
    }
}
